import { Vazirmatn } from "next/font/google";
import "./globals.css";
import Footer from "@/app/components/Footer";
import Providers from "./providers";
import Navigation from "./components/Navigation";

const inter = Vazirmatn({ subsets: ["latin"] });

export const metadata = {
  title: "ceve application",
  description: "Generated by deanj",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navigation />
          <div>
            <div className="bg-[#f7d9cd]">{children}</div>
            <div className="bottom-0">
              <Footer />
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
